dist: xenial
language: clojure
before_script:
- npm install -g karma-cli
- npm install
script:
- lein clean
- lein doo chrome-headless test once
before_deploy:
- lein clean
- lein cljsbuild once min
- lein jsass once
deploy:
  provider: firebase
  on:
    branch: master
  skip_cleanup: true
env:
  global:
    secure: D3t9dqKxKQJiVVRFhaR6+xoJg03taRvsC8F7JgeFrc4sUbEbVz3bvB8x4sJmjdQy1DzwsozZPjl7LLMjpDCFTV+IBx0rK/biJf/x70i54M8tRHRCejapVRUZSiwx4nvmkeC0kGM9bAguWOYZZsPCixXYV+c4DT9+73N8bjJbtb+l/SQqWnbB72AH5xZNtusRUgynpm/oZbPgqxCmB+JUTRCrqiU394jmIFL5KXnKPyporXK6KPh3/46+YNXXXMkegHHxjb6fKFUKrGuYfTy3NzcTHVuy53qwlwrUNIbR/QpcEND9BcidvbP7C5VL38p4MZ+f1yphN5zk8m2KGNZKeXfVRTRDq3LOaBLPVT5kuw3QIC4VKGoRob/ElbQPLV2FtIQdnLZF1q8GVkSIe5E9TcMzhnrlL/8Mgv0Ht2J1LlJY4ebJinX11HDGoUwsTsL07vV/K3ULZytnQzIcqXuBm8MGjdKNmO/dEvSjCopf0dMQt9bl8MLddyeuVYpQa8bbhybB+K/yHsrZN8o0OQQAfSZfTSU+8/bg+EELJ/GQWLCI3QeQbkmUlCczd0vYHD9kcB0MJTq9W0eLfsZTFWc51bbEg/IB3M7d40aCm3/TAKo8u7GnFb4AjyFI61YhjQDKZIpJ1WxpWBFpbnehP8n6RAnW1EJRoblVEeIdvX+lZVw=
